listen=YES
listen_ipv6=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

chroot_local_user=YES
allow_writeable_chroot=YES

local_umask=022

xferlog_enable=YES
xferlog_file=/honeypot-logs/vsftpd.log

pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
pasv_address=10.100.102.73 #to be changed depending on the server ip
